# Generated by Django 4.2.1 on 2023-07-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Ramadan', 'Ramadan')], max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('break_time', models.TimeField()),
                ('class_duration', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
