# Generated by Django 4.2.1 on 2023-07-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='break_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timing',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
