# Generated by Django 4.2.1 on 2023-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_break_time_remove_course_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
