# Generated by Django 4.2.1 on 2023-07-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_timing_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classentry',
            name='timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.timing'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[['Running', 'Running'], ['Suspended', 'Suspended']], default='Running'),
        ),
        migrations.CreateModel(
            name='SuspensionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended_since', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
