# Generated by Django 4.2.1 on 2023-07-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_classentry_timing_course_status_suspensiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspensiontime',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', unique=True),
        ),
    ]
