# Generated by Django 4.2.1 on 2023-07-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_suspensiontime_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensiontime',
            name='resume_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timing',
            name='break_duration',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='timing',
            name='rest_btw_classes',
            field=models.IntegerField(default=5),
        ),
    ]
