# Generated by Django 4.2.1 on 2023-09-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_timing_break_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Institution',
            new_name='institution',
        ),
    ]
