# Generated by Django 4.2.1 on 2023-09-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_institution_course_institution'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classentry',
            table='class_entries',
        ),
        migrations.AlterModelTable(
            name='commitment',
            table='commitments',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='institution',
            table='institutions',
        ),
        migrations.AlterModelTable(
            name='publicholidays',
            table='public_holidays',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
