# Generated by Django 4.2.1 on 2023-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_classentry_table_alter_commitment_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='typeOf',
            field=models.CharField(choices=[('ACADEMIC', 'ACADEMIC'), ('NON-ACADEMIC', 'NON-ACADEMIC'), ('EXAM', 'EXAM')], max_length=128),
        ),
        migrations.AlterModelTable(
            name='coursegroup',
            table='c_groups',
        ),
        migrations.AlterModelTable(
            name='suspensiontime',
            table='suspension_time',
        ),
        migrations.AlterModelTable(
            name='timing',
            table='timings',
        ),
    ]
