# Generated by Django 4.2.1 on 2023-09-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_topic_typeof_alter_coursegroup_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='typeOf',
            field=models.CharField(choices=[('ACADEMIC', 'ACADEMIC'), ('NON-ACADEMIC', 'NON-ACADEMIC'), ('EXAM', 'EXAM')], db_column='t_type', max_length=128),
        ),
    ]
