# Generated by Django 4.2.1 on 2023-09-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_topic_typeof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='typeOf',
            new_name='t_type',
        ),
    ]
