# Generated by Django 4.2.1 on 2023-09-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_examsupervisor_is_deleted_lecturer_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensiontime',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
