# Generated by Django 4.2.1 on 2023-09-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_suspensiontime_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='role',
            field=models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('ASSISTANT', 'ASSISTANT'), ('SECONDARY', 'SECONDARY')], max_length=128),
        ),
        migrations.AlterField(
            model_name='timing',
            name='timing',
            field=models.CharField(choices=[('SUMMER', 'SUMMER'), ('WINTER', 'WINTER'), ('RAMADAN', 'RAMADAN')], max_length=128),
        ),
    ]
