# Generated by Django 4.2.1 on 2023-09-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_classlecturer_is_deleted_classsupervisor_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classentry',
            name='exam_supervisors',
            field=models.ManyToManyField(blank=True, through='courses.ClassSupervisor', to='courses.examsupervisor'),
        ),
        migrations.AlterField(
            model_name='classentry',
            name='lecturers',
            field=models.ManyToManyField(blank=True, through='courses.ClassLecturer', to='courses.lecturer'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('class_duration', models.IntegerField()),
                ('timing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.timing')),
            ],
            options={
                'db_table': 'class_schedule',
            },
        ),
    ]
