# Generated by Django 4.2.1 on 2023-09-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_classschedule_is_deleted_alter_timing_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classentry',
            name='class_num',
        ),
        migrations.AddField(
            model_name='classentry',
            name='class_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.classschedule'),
        ),
    ]
