# Generated by Django 4.2.1 on 2023-09-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_classentry_class_num_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classentry',
            unique_together={('course_group', 'entry_date', 'class_schedule')},
        ),
    ]
