# Generated by Django 4.2.1 on 2023-09-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_classentry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classentry',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
