# Generated by Django 4.2.1 on 2023-09-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_classentry_entry_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commitment',
            table='old_commitments',
        ),
    ]
