# Generated by Django 4.2.1 on 2023-09-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_commitment_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='classentry',
            name='lecturers',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='lecturer',
        ),
        migrations.AlterModelTable(
            name='commitment',
            table='commitments',
        ),
        migrations.DeleteModel(
            name='ClassLecturer',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
