# Generated by Django 4.2.1 on 2023-09-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_remove_lecturer_courses_remove_classentry_lecturers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classentry',
            name='users',
            field=models.ManyToManyField(blank=True, through='courses.Commitment', to='courses.user'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='class_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.classentry'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.user'),
        ),
    ]
