# Generated by Django 4.2.1 on 2023-09-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_user_users_name_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classentry',
            unique_together=set(),
        ),
    ]
