# Generated by Django 4.2.1 on 2023-09-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_classentry_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('course_group', 'entry_date', 'class_schedule'), name='entries_sched_time'),
        ),
    ]
