# Generated by Django 4.2.1 on 2023-09-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_user_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('CONTRACTED', 'CONTRACTED'), ('EXTERNAL', 'EXTERNAL'), ('COMMITTEE', 'COMMITTEE')], max_length=128),
        ),
    ]
