# Generated by Django 4.2.1 on 2023-09-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_user_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsupervisor',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='classentry',
            name='exam_supervisors',
        ),
        migrations.DeleteModel(
            name='ClassSupervisor',
        ),
        migrations.DeleteModel(
            name='ExamSupervisor',
        ),
    ]
