# Generated by Django 4.2.1 on 2023-09-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_remove_examsupervisor_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='class_duration',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='rest_btw_classes',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='start_time',
        ),
    ]
