# Generated by Django 4.2.1 on 2023-11-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_commitment_role_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
