# Generated by Django 4.2.1 on 2023-12-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_user_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('party', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.user')),
            ],
            options={
                'db_table': 'training_courses',
            },
        ),
        migrations.CreateModel(
            name='ScientificDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sci_degree', models.CharField(max_length=128)),
                ('educational_institution', models.CharField(max_length=128)),
                ('major', models.CharField(max_length=128)),
                ('year_obtained', models.IntegerField()),
                ('grade', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.user')),
            ],
            options={
                'db_table': 'scientific_degrees',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=128)),
                ('certif_provider', models.CharField(max_length=128)),
                ('year_obtained', models.IntegerField()),
                ('validity', models.SmallIntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.user')),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
    ]
