# Generated by Django 4.2.1 on 2023-12-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_alter_certificate_validity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Riyadh, Al-andalus, Mizrid bin dirar St.', max_length=220),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=33),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='call',
            field=models.CharField(default='0544912111', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='training@watani.com', max_length=220),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Saudi Arabia', max_length=128),
            preserve_default=False,
        ),
    ]
