# Generated by Django 4.2.1 on 2024-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_user_address_user_age_user_call_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='validity',
            field=models.SmallIntegerField(choices=[(-1, 'مدى الحياة'), (1, 'سنة واحدة'), (5, 'خمس سنوات')]),
        ),
        migrations.AlterField(
            model_name='scientificdegree',
            name='sci_degree',
            field=models.CharField(choices=[('HIGH_SCHOOL', 'الدراسة الثانوية'), ('DIPLOMA', 'دبلوم'), ('BACHELOR', 'بكالوريوس'), ('MASTER', 'الماجستير'), ('DOCTORAL', 'دكتوراه')], max_length=128),
        ),
        migrations.AlterField(
            model_name='topic',
            name='t_type',
            field=models.CharField(choices=[('ACADEMIC', 'أكاديمي'), ('NON-ACADEMIC', 'غير أكاديمي'), ('EXAM', 'إمتحان'), ('INITIAL', 'إبتدائية')], db_column='t_type', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('INTERNAL-1', 'منسوب مدرسة سلاح الإشارة'), ('INTERNAL-2', 'منسوب وزارة الحرس الوطني'), ('CONTRACTED-1', 'مقاول - شركات'), ('CONTRACTED-2', 'مقاول - أفراد'), ('EXTERNAL', 'مقاول - حر'), ('COMMITTEE', 'منسوب مدرسة سلاح الإشارة - لِجان')], max_length=128),
        ),
    ]
