# Generated by Django 4.2.1 on 2024-01-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_alter_certificate_validity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('can_oversee_multiple_classes', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_sources',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='source',
        ),
    ]
