# Generated by Django 4.2.1 on 2024-01-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_source_remove_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.source'),
        ),
    ]
