# Generated by Django 4.2.1 on 2024-02-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_user_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classentry',
            index=models.Index(fields=['is_deleted'], name='ix_class_entries_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['is_deleted'], name='ix_class_schedule_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['is_deleted'], name='ix_commitments_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_deleted'], name='ix_courses_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='coursegroup',
            index=models.Index(fields=['is_deleted'], name='ix_c_groups_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['is_deleted'], name='ix_institutions_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='publicholidays',
            index=models.Index(fields=['is_deleted'], name='ix_public_holidays_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='suspensiontime',
            index=models.Index(fields=['is_deleted'], name='ix_suspension_time_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='timing',
            index=models.Index(fields=['is_deleted'], name='ix_timings_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_deleted'], name='ix_topics_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='ix_users_is_deleted'),
        ),
    ]
