# Generated by Django 4.2.1 on 2024-02-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_alter_user_address_alter_user_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='training_facility',
        ),
    ]
