# Generated by Django 4.2.1 on 2024-02-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_remove_topic_training_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='t_type',
            field=models.CharField(choices=[('ACADEMIC', 'أكاديمي'), ('NON-ACADEMIC', 'غير أكاديمي'), ('EXAM', 'إمتحان'), ('TIME_GAP', 'فاصل زمني'), ('INITIAL', 'حصص إبتدائية')], db_column='t_type', max_length=128),
        ),
    ]
